#!/bin/bash

FILE=jonesforth

echo "#!/bin/bash" > $FILE
echo "#auto generated by $(pwd)/make-jonesforth-script.sh" >> $FILE
echo "cat $(pwd)/jonesforth.f - | $(pwd)/jonesforth-core $@" >> $FILE

chmod +x $FILE
